baseURL = "https://example.org/"
languageCode = "pt-br"
title = "Troli's Mind"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

# Configuração dos menus - nome, referência e ordem
[menu]

  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 40

# Parâmetros do tema e site
[params]
  description = "Backup do cérebro sobre assuntos tech, sociais, cultura e filosofia"
  author = "Troli"

# Configurações do rodapé
  [params.footer]
    enable = true
    copyright = "© 2025 Troli's Mind — Conteúdo com autenticidade, profundidade e contexto"

# Configurações do Markdown e sintaxe de destaque
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

# Configuração de permalinks para refletir URLs padronizadas
[permalinks]
  sobre = "/sobre/"

# Sitemap configurado para trazer URLs importantes e organização
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Configuração SEO e social sharing (caso deseje expandir)
[params.seo]
  enable = true
  twitterCard = "summary_large_image"
  defaultImage = "/images/og-default.jpg"

# Hextra configurações específicas, caso queira usar
[params.hextra]
  showThemeCredit = false

